apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helloworld-controller
  namespace: shipshape
subjects:
  - kind: ServiceAccount
    name: helloworld-controller
    namespace: shipshape
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helloworld-controller
