version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - RupertBothma
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - RupertBothma
    labels:
      - ci

  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - RupertBothma
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /controller
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - RupertBothma
    labels:
      - dependencies
