apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-cert
spec:
  secretName: placeholder-tls
  issuerRef:
    kind: ClusterIssuer
    name: placeholder-issuer
  dnsNames:
    - placeholder.local
