apiVersion: v1
kind: ConfigMap
metadata:
  name: app-vars
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  ENV: prod
  HOSTNAME: prod.helloworld.shipshape.example.com
  TLS_SECRET_NAME: helloworld-prod-tls
  CLUSTER_ISSUER: letsencrypt-prod
  MESSAGE: hello from prod environment
