apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: VirtualService
      name: helloworld-virtualservice
    patch: |
      - op: replace
        path: /spec/http/0/timeout
        value: 15s
      - op: replace
        path: /spec/http/0/retries/attempts
        value: 3
      - op: replace
        path: /spec/http/0/retries/perTryTimeout
        value: 5s
